# Generated by Django 2.2.7 on 2019-11-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20191112_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='nombre',
            new_name='producto',
        ),
    ]
