# Generated by Django 2.2.7 on 2019-11-14 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichero',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
