# Generated by Django 2.2.7 on 2019-11-14 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_fichero_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichero',
            name='fecha',
        ),
    ]
