# Generated by Django 2.2.7 on 2019-11-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_fichero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fichero',
        ),
    ]
